- name: variables
  hosts: web
  connection: local
  vars: #play level variables
    course: "DEVOPS with AWS"
    trainer: siva
    duration: 120HRS
  tasks:
  - name: print variables
    ansible.builtin.debug:
      mgs: "course name is "

- name: Play2
  hosts: local
  connection: local #to manage local - server residing on own server
  tasks:
  - name: task2
    ansible.builtin.debug:
      msg: "Hello: self healer"     