- name: Prompting values
  hosts: local
  connection: local
  vars_prompt:
  - name: course
    prompt: Please enter course name
  - name: trainer
    private: false
    prompt: Please enter trainer name
  tasks:
  - name: print variable from files
    ansible.builtin.debug:
      msg: " name {{ course }} , triner {{ trainer }}"