- name: loop install packages
  hosts: web
  become: yes
  tasks: 
  - name: loop install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'gcc', state: 'absent' }
    - { name: 'mysql', state: 'absent' }
    - { name: 'zip', state: 'present' }