- name: Filters in Ansible
  hosts: local
  connection: local
  vars:
  tasks: 
  - name: Filters demo
    ansible.builtin.debug:
      msg: " person is {{ ask | default('Rakesh') }}"

  - name: convert string to list
    vars:
      fruits: "apple, orange, banana"
    ansible.builtin.debug:
      msg: " fruits are {{ fruits | split(',') }}"

  - name: convert map to list
    vars:
      course:
        course: DevOps
        duration: 120hrs
        trainer: sivakumar reddy
    ansible.builtin.debug:
      msg: " {{ course | dict2items }}"