- name: Filters in Ansible
  hosts: local
  connection: local
  vars:
    course:
    - course: DevOps
    - duration: 120hrs
    - trainer: sivakumar reddy
  tasks: 
  - name: Filters demo
    ansible.builtin.debug:
      msg: " person is {{ ask | default('Rakesh') }}"

  - name: convert string to list
    vars:
      fruits: "apple, orange, banana"
    ansible.builtin.debug:
      msg: " fruits are {{ fruits | split(',') }}"