- name: paly1
  hosts: web
  become: yes 
  tasks:
  - name: task1
    ansible.builtin.package:
      name: nginx
      state: installed
  - name: task2
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes 
      

